# Generated by Django 3.0.8 on 2020-07-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='yaxis',
            field=models.CharField(choices=[('t', 'C&deg;'), ('p', 'atm'), ('v', 'm3 per hour'), ('o', 'oee')], max_length=10),
        ),
    ]
