# Generated by Django 3.0.8 on 2020-07-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20200729_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='unit',
            field=models.CharField(choices=[('t', 'Co;'), ('f', 'F'), ('m', 'm3 per hour'), ('o', 'oee'), ('mmrtst', 'mm.tr.st'), ('s', 'kol-vo'), ('ts', 't shtuk'), ('P', 'Pa')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
