# Generated by Django 3.0.8 on 2020-07-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_point_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataoee',
            name='datetimeStart',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
