# Generated by Django 3.0.8 on 2020-07-29 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('childModel', models.CharField(choices=[('real', 'Real type variable'), ('bool', 'Boolean variable'), ('oee', 'Data OEE')], max_length=50)),
                ('yaxis', models.CharField(choices=[('t', 'C&deg;'), ('p', 'atm'), ('v', 'm3 per hour')], max_length=10)),
                ('warning', models.FloatField(null=True, verbose_name='warning')),
                ('alarm', models.FloatField(null=True, verbose_name='alarm')),
                ('stop', models.FloatField(null=True, verbose_name='stop')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Line')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Association')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Manufacture'),
        ),
        migrations.CreateModel(
            name='DataOEE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField(null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Point')),
            ],
        ),
        migrations.CreateModel(
            name='DataBoolean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('value', models.BooleanField(null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Point')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField(null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Point')),
            ],
        ),
    ]
