# Generated by Django 3.0.8 on 2020-07-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_dataoee_datetimestart'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataoee',
            name='name',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
