# Generated by Django 3.0.8 on 2020-07-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20200730_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='childModel',
            field=models.CharField(choices=[('real', 'Real type variable'), ('int', 'Int type variable'), ('bool', 'Boolean variable'), ('q', 'quit boolean variable'), ('i', 'input boolean variable'), ('m', 'Memory boolean variable'), ('oee', 'Data OEE')], max_length=50),
        ),
    ]
