# Generated by Django 3.0.8 on 2020-08-03 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20200730_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataoee',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Connections'),
        ),
        migrations.AlterField(
            model_name='point',
            name='endRead',
            field=models.IntegerField(null=True, verbose_name='end Read address +1 plc (for bit set bit number)'),
        ),
        migrations.AlterField(
            model_name='point',
            name='startRead',
            field=models.IntegerField(null=True, verbose_name='start  Read address plc (for bit  set number byte in plc)'),
        ),
        migrations.AlterField(
            model_name='point',
            name='startWrite',
            field=models.IntegerField(null=True, verbose_name='start  Write address plc '),
        ),
        migrations.AlterField(
            model_name='point',
            name='unit',
            field=models.CharField(choices=[('t', 'Co;'), ('f', 'F'), ('k', 'kg'), ('m', 'm3 per hour'), ('o', 'oee'), ('mmrtst', 'mm.tr.st'), ('s', 'kol-vo'), ('ts', 't shtuk'), ('P', 'Pa')], max_length=10),
        ),
        migrations.AlterField(
            model_name='point',
            name='yaxis',
            field=models.CharField(choices=[('t', 'C&deg;'), ('p', 'atm'), ('ves', 'ves'), ('v', 'm3 per hour'), ('o', 'oee')], max_length=10),
        ),
    ]
